# Generated by Django 2.2.4 on 2021-02-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='city',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='state',
            new_name='last_name',
        ),
    ]
